# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w-Avol0o18j3APEoYJw0Cgjm_YfHmRG0
"""

cd C:/Users/ELCOT/Desktop/deva

!unzip '/deva/Dataset.zip'

from keras.preprocessing.image import ImageDataGenerator

train_datagen = ImageDataGenerator(rescale=1./255,shear_range=0.2,zoom_range=0.2,horizontal_flip=True)
test_datagen=ImageDataGenerator(rescale=1./255)

from tensorflow.keras.models import load_model

from keras.preprocessing import image

!pip install flask

from flask import Flask,render_template,request

import os
import numpy as np
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image
import requests

app= Flask(__name__,template_folder="templates")

!pip install keras==2.7.0
!pip install tensorflow==2.7.0

!pip install watson-machine-learning-client --upgrade

from ibm_watson_machine_learning import APIClient
credentials ={
    "url":"https://us-south.ml.cloud.ibm.com",
    "apikey": "KiGgdaOCPso0Tcmw48K5yRWXh1qQp59HzR_wUyyVNJQI"
}
client = APIClient(credentials)
client

client.spaces.get_details()

def guid_from_space_name(client,deploy):
  space = client.spaces.get_details()
  return (next(item for item in space['resources'] if item['entity']['name']==deploy)['metadata']['id'])

space_uid = guid_from_space_name(client,'IBM cloud')
print("Space UID = " + space_uid)

client.set.default_space(space_uid)

client.software_specifications.list(limit=100)

software_space_uid = client.software_specifications.get_uid_by_name('tensorflow_rt22.1-py3.9')
software_space_uid

from tensorflow.keras.models import load_model
from keras.preprocessing import image
from PIL import Image
import numpy as np

import os, types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0
# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share the notebook.
cos_client = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='Ow2yOgDRSD8Q4N3az2cF70vRSu9Yy7Hdr3Ehr56S7Zvj',
    ibm_auth_endpoint="https://iam.cloud.ibm.com/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3.private.us.cloud-object-storage.appdomain.cloud')

bucket = 'ainutritionanalyzer-donotdelete-pr-trm8wntzlopso0'
object_key = 'n07740461_158.jpg'

streaming_body_2 = cos_client.get_object(Bucket=bucket, Key=object_key)['Body']

# Your data file was loaded into a botocore.response.StreamingBody object.
# Please read the documentation of ibm_boto3 and pandas to learn more about the possibilities to load the data.
# ibm_boto3 documentation: https://ibm.github.io/ibm-cos-sdk-python/
# pandas documentation: http://pandas.pydata.org/

img = Image.open(streaming_body_1).convert("L") # convert image to monochrome
img = img.resize( (28,28) ) # resizing of input image